### ISSUE TITLE
Use the shadcn scrollarea component to make the UI cleaner

### ISSUE THREAD

**Issue by ghost** [Georgegriff/react-dnd-kit-tailwind-shadcn-ui#3]
Shadcn provides [Scroll-area](https://ui.shadcn.com/docs/components/scroll-area) component to make the scrolling sections more clear and go hand in hand with the theming. 

Here is how it looks with the shadcn Scroll-area - 

![2023-11-20 11_19_22-Greenshot](https://github.com/Georgegriff/react-dnd-kit-tailwind-shadcn-ui/assets/134765302/16bbf300-9ccd-4e2c-ba30-06e547d6a2c6)

Current implementation - 

![2023-11-20 11_19_36-Greenshot](https://github.com/Georgegriff/react-dnd-kit-tailwind-shadcn-ui/assets/134765302/f1620d66-d647-4d6d-b76a-527d060286d3)

I'd like to know if you like using the shadcn Scroll-area. If so, I can help you with a PR.

Thank you 😊

**Comment by Georgegriff** [comment]
thanks! This repo was just a throw-away demo, didn't expect it to pick up traction! but if you have a fix I'd be open to learning from how to do things better. This was my first project with tailwind

**Comment by ghost** [comment]
Hey, thanks for sharing your thoughts on the project! Even though it was supposed to be just a throw-away demo, your project turned out to be super useful and valuable for the community. Let me know if you're interested in further developing it, I'd be happy to assist. Your dedication to the community is just amazing and I appreciate all the hard work you've done.

**Comment by Georgegriff** [comment]
Thanks for the suggestion, I've implemented this, and it looks much nicer!

<img width="1321" alt="image" src="https://github.com/Georgegriff/react-dnd-kit-tailwind-shadcn-ui/assets/9056958/a7860872-e4f9-47d9-8a5f-7f426f2c78d2">

https://github.com/Georgegriff/react-dnd-kit-tailwind-shadcn-ui/commit/ec6ded122bfb1245dbde3070bf3e5116f74dc20e
